### ISSUE TITLE
Jupyter lab just says loading widget

### ISSUE THREAD

**Issue by ari62** [zhihanyue/qgridnext#1]
### Environment

* Operating System:
macOs Ventura 13.5.1
Macbook Pro 16-inch 2021
Chip: M1 Max
Browser: Chrome 120.0.0.6099.234 (Official Build) (arm64)
Jupyterlab 4.1.0
* Python Version: `$ python --version`
` Python 3.9.13
`
* Python packages: `$ pip freeze` or `$ conda list` (please include qgridnext, pandas, ipywidgets, jupyterlab/notebook versions)
see attached 
[pipfreeze.txt](https://github.com/zhihanyue/qgridnext/files/14229919/pipfreeze.txt)

* Jupyter lab packages (if applicable): `$ jupyter labextension list`
```
 jupyter labextension list
JupyterLab v4.1.0
/Users/user/opt/anaconda3/share/jupyter/labextensions
        qgridnext v2.0.0 enabled OK (python, qgridnext)
        jupysql-plugin v0.2.6 enabled  X (python, jupysql-plugin)
        jupyterlab-plotly v5.9.0 enabled  X
        @jupyter-server/resource-usage v1.0.1 enabled OK (python, jupyter-resource-usage)
        @pyviz/jupyterlab_pyviz v2.0.2 enabled  X (python, pyviz_comms)
        @jupyter-lsp/jupyterlab-lsp v5.0.3 enabled OK (python, jupyterlab-lsp)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled  X (python, jupyterlab_widgets)


   The following extensions are outdated:
        jupysql-plugin
        jupyterlab-plotly
        @pyviz/jupyterlab_pyviz
        @jupyter-widgets/jupyterlab-manager
        
   Consider checking if an update is available for these packages.

Other labextensions (built into JupyterLab)
   app dir: /Users/user/opt/anaconda3/share/jupyter/lab
        jupyter-matplotlib v0.11.3 enabled OK
        jupyterlab-dash v0.4.2 enabled  X
        jupyterlab-flake8 v0.7.1 enabled  X

   The following extensions are outdated:
        jupyterlab-dash
        jupyterlab-flake8
        
   Consider checking if an update is available for these packages.



Disabled extensions:
    @jupyterlab/completer-extension:base-service
    @jupyterlab/fileeditor-extension:language-server
    @jupyterlab/lsp-extension:settings
    @jupyterlab/notebook-extension:language-server

The following source extensions are overshadowed by older prebuilt extensions:
    @jupyter-widgets/jupyterlab-manager

```
### Description of Issue
Expectation:
widget loads and is display
* What happened instead?
Just says Loading widget...
See screenshot
<img width="682" alt="SCREE" src="https://github.com/zhihanyue/qgridnext/assets/8607924/0392d2d3-1844-4cdd-a776-bb13b713faf0">

### Reproduction Steps
```
from qgrid import show_grid
show_grid(myDF)
```
...

### What steps have you taken to resolve this already?
Ran jupyter lab build , issue persists
...

### Anything else?

no

**Comment by ari62** [comment]
Fixed it. Solution was to
` pip install -U ipywidgets
`
Which changed to these versions:

```
    Uninstalling ipywidgets-7.6.5:
      Successfully uninstalled ipywidgets-7.6.5
Successfully installed comm-0.2.1 ipywidgets-8.1.2 jupyterlab-widgets-3.0.10 widgetsnbextension-4.0.10

```

**Comment by zhihanyue** [comment]
There appears to be an issue stemming from incompatibility between the older version of ipywidgets and the new JupyterLab 4. To address this, it is recommended to upgrade to the latest version of ipywidgets. For example, your current version of @jupyter-widgets/jupyterlab-manager is 3.0.0, which needs to be updated to version 5.0 or higher.

Note: ensure that you are working within a clean environment before making any updates to avoid potential conflicts. The following warning may be due to multiple versions of ipywidget installed.
> The following source extensions are overshadowed by older prebuilt extensions:
>     @jupyter-widgets/jupyterlab-manager

https://github.com/zhihanyue/qgridnext/tree/main/test_envs
We have tested on JupyterLab 4.1.0 with the environment `py311-lab4-nb7-vl05` provided here. By conducting a test in this specified environment, you can quickly ascertain whether the issue is related to your current environment, allowing for further steps to resolve the issue.

**Comment by fizzofizzzz** [comment]
Thank you so much for qgridnext! I was struggling a lot to fix the old qgrid. It took me days!
